### ISSUE TITLE
ERROR: Could not find suitable machine to run html2textNode_component

### ISSUE THREAD

**Issue by olyerickson** [IKCAP/wings#21]
Saw the error above (screen shot below) when attempting to run the English_Words file comparison workflow using the exact settings from the Tutorial http://www.wings-workflows.org/tutorial/workflowUser#Setting_Up_a_Workflow_by_Selecting_Data_and_Parameters

attached: screen shot of error screen
![selection_477](https://cloud.githubusercontent.com/assets/358649/10462720/383e4178-71ae-11e5-85bc-cf8c6a8c9e0e.png)

**Comment by olyerickson** [comment]
Attached is a screen shot of the input selections
![selection_479](https://cloud.githubusercontent.com/assets/358649/10462840/d1bb4e86-71ae-11e5-93c2-9f40b01327b6.png)

**Comment by IKCAP** [comment]
Hmm, in "Manage Components", you will find that html2text component has some Dependencies (in the dependency tab). Try to remove then and try again. (This is what I had tried to remove in the last domain update for CompareFiles, but it appears that it still exists).

**Comment by olyerickson** [comment]
There were no dependencies set (see attached)
![selection_480](https://cloud.githubusercontent.com/assets/358649/10464240/c7b3adf4-71b6-11e5-82bb-b73099b830e9.png)

**Comment by IKCAP** [comment]
Ah, sorry I didn't notice the memory requirement error earlier in your first screenshot. If you go to the "Describe Resources" page, and set the appropriate system memory for Localhost, it should work.

**Comment by olyerickson** [comment]
That definitely helped; the workflow was successfully created. But execution had issues; see this from the log...

html2textNode
----------------------
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/run -o1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Text1-1yj1h1k7w1q8yj4wkt22a4zw6 -i1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/en_San_Francisco.html
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/run: 22: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/io.sh: Syntax error: Bad for loop variable


html2textNode_1
----------------------
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/run -o1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Text2-2j7wpw4aus2sb45qc44r6ygci -i1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/en_France.html
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/run: 22: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/io.sh: Syntax error: Bad for loop variable

Finished
Finished

**Comment by IKCAP** [comment]
It looks like an incompatibility with the shell. Do you have bash installed ?

**Comment by olyerickson** [comment]
Of course...
GNU bash, version 4.3.11(1)-release (i686-pc-linux-gnu)

**Comment by IKCAP** [comment]
Could you try to run the commands shown in the log manually on the terminal to see if it gives the same error ?

**Comment by olyerickson** [comment]
Yes, same error when run from shell directly:
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/run: 22: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/io.sh: Syntax error: Bad for loop variable

**Comment by IKCAP** [comment]
Ok, I think it happens because the default shell /bin/sh isn’t soft linked to /bin/bash on your machine. I shouldn’t have assumed that in the components. You could create a soft link for now just to test if it works, but ideally I should fix the component scripts. The way to fix the components would be to have the first line of the run scripts be:

#!/bin/bash

instead of

#!/bin/sh

The run script for your example is /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/run

**Comment by olyerickson** [comment]
AH, I see. I did check the io.sh and the hashbang was correct, but didn't check the run. Once I changed run, it worked. 

Please let me know the easiest fix e.g. soft-linking bin/sh to bin/bash

Thanks!

**Comment by IKCAP** [comment]
Yes soft linking /bin/sh to /bin/bash would be the easiest fix for now (if it doesn’t break anything else on your system).

**Comment by olyerickson** [comment]
/bin/sh already appears to be soft linked to /bin/bash; when I do ```echo $SHELL``` I see ```bash```

I'm on Mint 17.2, not Ubuntu....

**Comment by olyerickson** [comment]
In order to try to get the complete workflow to run I changed the shebang in ```run``` for 

Most scripts worked but some still failed; for example note the Permission Denied (below)
```
removePatternNode_3
----------------------
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/removePattern/run -o1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/CleanWords2-adg5rjfjlxj66dvc5zu974jzr -i1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/NonTrivialWords2-4uu5meba1boa28zv17cq56890 -i2 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/en_trivials
Input1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/NonTrivialWords2-4uu5meba1boa28zv17cq56890
Input2: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/en_trivials
Outputs1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/CleanWords2-adg5rjfjlxj66dvc5zu974jzr


removePatternNode_2
----------------------
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/removePattern/run -o1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/NonTrivialWords2-4uu5meba1boa28zv17cq56890 -i1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Words2-4rxpopepdxt0ae0zy19zp5tc6 -i2 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/specialchars
Input1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Words2-4rxpopepdxt0ae0zy19zp5tc6
Input2: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/specialchars
Outputs1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/NonTrivialWords2-4uu5meba1boa28zv17cq56890


html2textNode_1
----------------------
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/run -o1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Text2-2j7wpw4aus2sb45qc44r6ygci -i1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/en_France.html
Input1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/en_France.html
Outputs1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Text2-2j7wpw4aus2sb45qc44r6ygci


countDuplicatesNode_1
----------------------
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/countDuplicates/run -o1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/WordCountInDoc2-7siohpsexye2o5ubk94iatt57 -i1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/CleanWords2-adg5rjfjlxj66dvc5zu974jzr -i2 5
Input1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/CleanWords2-adg5rjfjlxj66dvc5zu974jzr
Input2: 5 (parameter)
Outputs1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/WordCountInDoc2-7siohpsexye2o5ubk94iatt57


getSortedWordsNode_1
----------------------
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/getSortedWords/run -o1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Words2-4rxpopepdxt0ae0zy19zp5tc6 -i1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Text2-2j7wpw4aus2sb45qc44r6ygci
Input1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Text2-2j7wpw4aus2sb45qc44r6ygci
Outputs1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Words2-4rxpopepdxt0ae0zy19zp5tc6


html2textNode
----------------------
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/run -o1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Text1-1yj1h1k7w1q8yj4wkt22a4zw6 -i1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/en_San_Francisco.html
Input1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/en_San_Francisco.html
Outputs1: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Text1-1yj1h1k7w1q8yj4wkt22a4zw6
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/run: line 25: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Text1-1yj1h1k7w1q8yj4wkt22a4zw6.met: Permission denied
Error

Finished
```

**Comment by olyerickson** [comment]
...and here is the pretty version of the results of the run
![selection_482](https://cloud.githubusercontent.com/assets/358649/10482313/3c28cf46-7245-11e5-99c1-3663ae332c1a.png)

**Comment by olyerickson** [comment]
The command
```
/usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/code/library/html2text/run -o1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/Text1-1yj1h1k7w1q8yj4wkt22a4zw6 -i1 /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/en_San_Francisco.html
```
...appears to work when I run it as sudo but gives a permission denied when I don't

**Comment by IKCAP** [comment]
Hmm, does the tomcat user have permissions to write in the /usr/share/tomcat7/storage/users/olyerickson/CompareFiles_2_/data/ folder ?

**Comment by olyerickson** [comment]
I don't recall setting tomcat permissions...

**Comment by olyerickson** [comment]
Seems to be working now. It's possible tomcat wasn't seeing ```tomcat-users.xml``` so I did...
```
sudo chown tomcat7:tomcat7 /var/lib/tomcat7/conf/tomcat-users.xml

```
Also, created the folder ```/var/lib/tomcat7/temp``` with tomcat permissions
```
sudo mkdir /var/lib/tomcat7/temp && sudo chown -R tomcat7:tomcat7 /var/lib/tomcat7/temp
```
I did this based on http://askubuntu.com/questions/516466/permission-issues-with-tomcat

Now seeing attached
![selection_484](https://cloud.githubusercontent.com/assets/358649/10484361/a48e0f08-7252-11e5-8cfe-17851d6c26c0.png)

**Comment by olyerickson** [comment]
I think you need a checklist of tomcat7 settings for the user to check, and what they should be set to...

**Comment by IKCAP** [comment]
Thanks for sorting this out John ! I will make sure to add the tomcat permissions checklist

**Comment by olyerickson** [comment]
Was a "tomcat permissions checklist" ever created? One of our students is having similar issues, is replicating my steps to fixing them, but some fix is missing...
